### ISSUE TITLE
Code of DTI-HETA

### ISSUE THREAD

**Issue by ljzengwenlian** [ZhangyuXM/DTI-HETA#1]
您好，最近有幸阅读到您发表的论文《DTI-HETAPredictionofdrug-targetinteractionsbasedonGCNandGATonheterogeneousgraph》，对其十分感兴趣，我想重点参考您的这篇文章,请问一下您能否分享一下开源代码，仅用于学术交流。

**Comment by ZhangyuXM** [comment]
您好，因本文代码为已毕业的同学（一作）编写，开源具体事宜需要他本人同意并亲自整理后才能进行。目前此项目作为数据集开源所用，所以感谢您的关注，后续有进展我们会及时更新。

**Comment by ljzengwenlian** [comment]
感谢您的回复，我会继续进行关注的，万分感谢！

**Comment by ljzengwenlian** [comment]
感谢您的回复，我会继续进行关注的，万分感谢！
